apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: orders-consumer-scaler
  namespace: keda-scaling

spec:
  scaleTargetRef:
    name: orders-consumer

  pollingInterval: 5          # ADDED: check lag every 5s instead of the 30s default

  minReplicaCount: 1
  maxReplicaCount: 5

  cooldownPeriod: 30

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 15
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15

  triggers:
  - type: kafka
    metadata:
      bootstrapServers: redpanda.keda-scaling.svc.cluster.local:9092
      consumerGroup: orders-group
      topic: orders
      lagThreshold: "10"
      activationLagThreshold: "0"
      offsetResetPolicy: "earliest"   # ADDED: matches your consumer's auto_offset_reset="earliest"
